[package]

name = "roomb"
version = "0.0.1"
authors = [ "Michael Vorotyntsev <linkofwise@gmail.com>" ]

[dependencies]
rand = "*"
log = "0.3"
env_logger = "0.3"
time = "0.1"
rust-crypto = "*"
rustc-serialize = "0.3"

[[bin]]

name = "roomb"
